#=========================================================================
# Generate Wrapper for OpenRAM SRAMs
#=========================================================================
# Author : Khalid Al-Hawaj
# Date   : March 3, 2020
#

name: openram-generate-wrapper

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - openram-cfg.list
  - design.v

outputs:
  - design.v

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - sh ./run.sh
