#!/usr/bin/env python
#=========================================================================
# pmx-sim [options] <elf-binary>
#=========================================================================
# This is the primary simulator we use to drive our processor,
# accelerator, memory compositions. By choosing an FL processor and
# accelerator implementation and no cache we can effectively create an
# ISA simulator, and by choosing RTL implementations we can create an RTL
# simulator and potentially use this simulator to drive the ASIC flow.
# Note that the simulator takes the elf binary, not the VMH file on the
# command line.
#
#  -h --help            Display this message
#
#  --proc-impl  <impl>  Processor implementation (see below)
#  --cache-impl <impl>  Cache implementation (see below)
#  --xcel-impl  <impl>  Accelerator implementation (see below)
#  --trace              Display line tracing
#  --trace-regs         Show regs read/written by each inst
#  --limit              Set max number of cycles, default=100000
#  --stats              Output stats about execution
#  --translate          Translate RTL model to Verilog
#  --dump-vcd           Dump VCD to imul-<impl>-<input>.vcd
#
#  <elf-binary>         Elf binary file for PARC ISA
#
# Processor Implementations:
#  - fl  : functional-level processor model
#  - rtl : register-transfer-level processor model
#
# Cache Implementations:
#  - null : no caches
#  - rtl  : register-transfer-level cache model
#
# Accelerator Implementation:
#  - null-rtl  : empty accelerator
#
# For tut9_xcel, the following accelerator impls are available:
#
#  - vvadd-fl  : vector-vector add accelerator FL model
#  - vvadd-cl  : vector-vector add accelerator CL model
#  - vvadd-rtl : vector-vector add accelerator RTL model
#  - accum-fl  : accumulator accelerator FL model
#  - accum-cl  : accumulator accelerator CL model
#  - accum-rtl : accumulator accelerator RTL model
#
# For lab2_xcel, the following accelerator impls are available:
#
#  - sort-fl   : sorting accelerator FL model
#  - sort-cl   : sorting accelerator CL model
#  - sort-rtl  : sorting accelerator RTL model
#
# Author : Christopher Batten
# Date   : February 26, 2016
#

# Variables used to make the simulator conditionally work for either
# tut9_xcel and/or lab2_xcel. In our labs repo, we keep both of these
# enabled, but when we release the code for the tutorial and lab we set
# these variables accordingly.

tut9_xcel_enabled = False
lab2_xcel_enabled = False
oflow_xcel_enabled = True

# Hack to add project root to python path

import os
import sys

sim_dir = os.path.dirname( os.path.abspath( __file__ ) )
while sim_dir:
  if os.path.exists( sim_dir + os.path.sep + ".pymtl_sim_root" ):
    sys.path.insert(0,sim_dir)
    break
  sim_dir = os.path.dirname(sim_dir)

import argparse
import re
import random

from pymtl3      import *
from pymtl3.passes.backends.verilog import VerilogPlaceholderPass, TranslationConfigs

from pymtl3.stdlib.cl.MemoryCL import MemoryCL
from pymtl3.stdlib.ifcs import mk_mem_msg, SendIfcRTL, RecvIfcRTL
from pymtl3.stdlib.test import config_model

from proc.SparseMemoryImage import SparseMemoryImage
from proc.test.harness      import TestHarness
from proc.tinyrv2_encoding  import assemble
from proc                   import ProcFL
from proc                   import ProcRTL
from proc                   import NullXcelRTL

from cache                  import BlockingCacheRTL

if tut9_xcel_enabled:
  from tut9_xcel              import VvaddXcelFL
  from tut9_xcel              import VvaddXcelCL
  from tut9_xcel              import VvaddXcelRTL
  from tut9_xcel              import AccumXcelFL
  from tut9_xcel              import AccumXcelCL
  from tut9_xcel              import AccumXcelRTL

if lab2_xcel_enabled:
  from lab2_xcel              import SortXcelFL
  from lab2_xcel              import SortXcelCL
  from lab2_xcel              import SortXcelRTL

if oflow_xcel_enabled:
  from final_project          import Optical_flowRTL

from pmx.ProcMemXcel            import ProcMemXcel
from pmx.ProcXcel               import ProcXcel

from proc.elf               import elf_reader

#=========================================================================
# Command line processing
#=========================================================================

class ArgumentParserWithCustomError(argparse.ArgumentParser):
  def error( self, msg = "" ):
    if ( msg ): print("\n ERROR: %s" % msg)
    print("")
    file = open( sys.argv[0] )
    for ( lineno, line ) in enumerate( file ):
      if ( line[0] != '#' ): sys.exit(msg != "")
      if ( (lineno == 2) or (lineno >= 4) ): print( line[1:].rstrip("\n") )

def parse_cmdline():
  p = ArgumentParserWithCustomError( add_help=False )

  # Standard command line arguments

  p.add_argument( "-h", "--help", action="store_true" )

  # Additional commane line arguments for the simulator

  p.add_argument( "--proc-impl", choices=["fl", "rtl"], default="fl" )
  p.add_argument( "--cache-impl", choices=["null", "rtl"], default="null" )

  xcel_impls = ["null-rtl"]

  if tut9_xcel_enabled:
    xcel_impls.extend([ "vvadd-fl", "vvadd-cl", "vvadd-rtl" ])
    xcel_impls.extend([ "accum-fl", "accum-cl", "accum-rtl" ])

  if lab2_xcel_enabled:
    xcel_impls.extend([ "sort-fl", "sort-cl", "sort-rtl" ])

  if oflow_xcel_enabled:
    xcel_impls.extend([ "oflow-rtl" ])

  p.add_argument( "--xcel-impl", choices=xcel_impls, default="null-rtl" )

  p.add_argument( "--trace",      action="store_true"      )
  p.add_argument( "--trace-regs", action="store_true"      )
  p.add_argument( "--limit",      default=50000000, type=int )
  p.add_argument( "--stats",      action="store_true"      )
  p.add_argument( "--translate",  action="store_true"      )
  p.add_argument( "--dump-vcd",   action="store_true"      )
  p.add_argument( "--perf",       default=0,  type=int )

  p.add_argument( "elf_file" )

  opts = p.parse_args()
  if opts.help: p.error()
  return opts

#=========================================================================
# TestHarness
#=========================================================================

class TestHarness( Component ):

  #-----------------------------------------------------------------------
  # constructor
  #-----------------------------------------------------------------------

  def construct( s, pmx, caches ):

    # Stats enable signal

    s.stats_en = OutPort()

    # prog2mngr interface. Note simulator only gets output, so we don't
    # need to worry about the mngr2proc interface. The simulator will
    # monitor this interface for handling various message types.

    s.mngr2proc = RecvIfcRTL( Bits32 )
    s.proc2mngr = SendIfcRTL( Bits32 )

    # Instantiate processor, cache, accelerator

    s.pmx = pmx

    # If pmx does not have any caches, we need a different test memory

    if caches:
      s.mem = MemoryCL( 2, [ mk_mem_msg(8,32,128) ] * 2, mem_nbytes=1<<28 )
    else:
      s.mem = MemoryCL( 3, [ mk_mem_msg(8,32,32) ] * 3, mem_nbytes=1<<28 )

    # Bring the stats enable up to the top level

    s.stats_en  //= s.pmx.stats_en

    # Processor <-> Proc/Mngr

    s.mngr2proc //= s.pmx.mngr2proc
    s.proc2mngr //= s.pmx.proc2mngr

    # PMX Caches <-> Memory

    s.pmx.imem //= s.mem.ifc[0]
    s.pmx.dmem //= s.mem.ifc[1]

    if not caches:
      # PMX directly to memory with no caches
      s.pmx.xmem //= s.mem.ifc[2]

  #-----------------------------------------------------------------------
  # load memory image
  #-----------------------------------------------------------------------

  def load( self, mem_image ):
    sections = mem_image.get_sections()
    for section in sections:
      start_addr = section.addr
      stop_addr  = section.addr + len(section.data)
      self.mem.mem.mem[start_addr:stop_addr] = section.data

  #-----------------------------------------------------------------------
  # line trace
  #-----------------------------------------------------------------------

  def line_trace( s ):
    return ("-" if s.stats_en else " ") + \
           s.pmx.line_trace() + " | " + \
           s.mem.ifc[1].line_trace()

#=========================================================================
# Main
#=========================================================================

def main():

  try:
    import pypyjit
    pypyjit.set_param("off")
  except:
    pass

  opts = parse_cmdline()

  #-----------------------------------------------------------------------
  # Load the elf file and do some hacky binary rewriting
  #-----------------------------------------------------------------------

  # Open elf binary

  mem_image = None
  with open(opts.elf_file,'rb') as file_obj:
    mem_image = elf_reader( file_obj )

  #-----------------------------------------------------------------------
  # Setup simulator
  #-----------------------------------------------------------------------

  # Determine which processor model to use in the simulator

  proc_impl_dict = {
    "fl"  : ProcFL,
    "rtl" : ProcRTL,
  }

  # Determine which accelerator model to use in the simulator

  xcel_impl_dict = {
    "null-rtl"  : NullXcelRTL,
  }

  if tut9_xcel_enabled:
    xcel_impl_dict["vvadd-fl"]  = VvaddXcelFL
    xcel_impl_dict["vvadd-cl"]  = VvaddXcelCL
    xcel_impl_dict["vvadd-rtl"] = VvaddXcelRTL
    xcel_impl_dict["accum-fl"]  = AccumXcelFL
    xcel_impl_dict["accum-cl"]  = AccumXcelCL
    xcel_impl_dict["accum-rtl"] = AccumXcelRTL

  if lab2_xcel_enabled:
    xcel_impl_dict["sort-fl"]   = SortXcelFL
    xcel_impl_dict["sort-cl"]   = SortXcelCL
    xcel_impl_dict["sort-rtl"]  = SortXcelRTL

  if oflow_xcel_enabled:
    xcel_impl_dict["oflow-rtl"] = Optical_flowRTL

  # Check if translation is valid

  if opts.translate:
    if    not opts.proc_impl == "rtl"  \
       or not opts.xcel_impl.endswith("rtl"):

      print("\n ERROR: --translate only works with RTL models \n")
      exit(1)


  # By default, PyMTL will keep creating different hash suffixes for our
  # ProcMemXcel since it is parameterized by module types. But this is
  # super annoying. So we explicitly tell PyMTL what to name the
  # resulting Verilog.

  # Create test harness with caches
  params={'image_column':128,
          'image_row':96,
          'window_size':3,
          'window_size_ext':5}
  if opts.cache_impl != "null":

    # If we have RTL cache, we'd want every part to be RTL

    if    not opts.proc_impl == "rtl"  \
       or not opts.xcel_impl.endswith("rtl"):

      print("\n ERROR: when cache-impl is RTL, we need RTL proc and RTL xcel!\n")
      exit(1) 
    if opts.xcel_impl == "null-rtl":
      pmx = ProcMemXcel( proc_impl_dict[ opts.proc_impl ](),
                       BlockingCacheRTL(), BlockingCacheRTL(),
                       xcel_impl_dict[ opts.xcel_impl ]() )
    else:
      pmx = ProcMemXcel( proc_impl_dict[ opts.proc_impl ](),
                       BlockingCacheRTL(), BlockingCacheRTL(),
                       xcel_impl_dict[ opts.xcel_impl ](**params) )
    pmx.config_verilog_translate = TranslationConfigs(
      translate = False,
      explicit_module_name = 'ProcMemXcel_' + opts.xcel_impl.replace('-','_')
    )

    model = TestHarness( pmx, caches=True )
 
  # Create test harness with no caches

  else:
    pmx = ProcXcel( proc_impl_dict[ opts.proc_impl ](),
                    xcel_impl_dict[ opts.xcel_impl ]() )
    pmx.config_verilog_translate = TranslationConfigs(
      translate = False,
      explicit_module_name = 'ProcXcel_' + opts.xcel_impl.replace('-','_')
    )

    model = TestHarness( pmx, caches=False )
    
  #model.set_param("top.Optical_flowRTL.construct",image_column=128,image_row=96,window_size=3,swindow_size_ext = 5)
  config_model( model, f"pmx-sim-{opts.xcel_impl}-{os.path.basename( opts.elf_file )}.vcd" if opts.dump_vcd else None,
                opts.translate, ['pmx'] )

  # Load the program into the model

  model.load( mem_image )

  # Apply placeholder pass

  model.apply ( VerilogPlaceholderPass() )

  # We can call apply if we are 100% sure the top level is not tagged

  model.apply( TranslationImportPass() )

  # Create a simulator
  from pymtl3.passes.mamba import Mamba2020
  model.apply( Mamba2020( line_trace=opts.trace ) )
  # model.apply( SimulationPass() )

  try:
    import pypyjit
    pypyjit.set_param("default")
    pypyjit.set_param("trace_limit=100000000")
  except:
    pass

  # Reset test harness

  model.sim_reset( print_line_trace=opts.trace )

  # We are always ready to accept a proc2mngr message

  model.proc2mngr.rdy = b1(1)

  #-----------------------------------------------------------------------
  # Run the simulation
  #-----------------------------------------------------------------------

  num_cycles = 0
  count      = 0

  # Storage for extra three messages on failure

  app_fail_xtra       = False
  app_fail_xtra_count = 0
  app_fail_xtra_msgs  = [ None, None, None ]

  # Storage for print

  app_print           = False
  app_print_type      = None  # 0: int, 1: char, 2: string

  import timeit
  start_time = timeit.default_timer()

  last_time = start_time
  while count < opts.limit:
    count = count + 1

    if opts.perf > 0 and count % opts.perf == 0:
      this_time = timeit.default_timer()
      print( f"cycle {count-opts.perf}-{count}: {opts.perf/(this_time - last_time)}")
      last_time = this_time

    # Generate line trace

    if opts.trace:
      model.print_line_trace()

    # Update cycle count

    if model.stats_en:
      num_cycles += 1

    # Check the proc2mngr interface

    if model.proc2mngr.en:

      msg_type = model.proc2mngr.msg[16:32]
      msg_xtra = model.proc2mngr.msg[ 0:16]

      # First we check if we are gathering app_fail_xtra_msgs

      if app_fail_xtra:
        app_fail_xtra_msgs[ app_fail_xtra_count ] = model.proc2mngr.msg[:]
        app_fail_xtra_count += 1
        if app_fail_xtra_count == 3:
          print( "" )
          print( "  [ FAILED ] dest[{0}] != ref[{0}] ({1} != {2})" \
                  .format( int(app_fail_xtra_msgs[0]),
                           int(app_fail_xtra_msgs[1]),
                           int(app_fail_xtra_msgs[2]) ) )
          print( "" )
          exit(1)

      # Then we check if we are doing a print

      elif app_print:

        # Print int

        if app_print_type == 0:
          print( model.proc2mngr.msg[:].uint(), end='' )
          app_print = False

        if app_print_type == 1:
          print( chr(model.proc2mngr.msg[:].uint()), end='' )
          app_print = False

        if app_print_type == 2:
          char_as_num = model.proc2mngr.msg[:].uint()
          if char_as_num > 0:
            print( chr(char_as_num), end='' )
          else:
            app_print = False

      # Message is from an assembly test

      elif msg_type == 0:

        if msg_xtra == 0:
          print( "" )
          print( "  [ passed ]##" )
          print( "" )
          break

        else:
          print( "" )
          print( "  [ FAILED ] error on line {}".format(msg_xtra.uint()) )
          print( "" )
          exit(1)

      # Message is from a bmark

      elif msg_type == 1:

        if msg_xtra == 0:
          break
        else:
          exit( msg_xtra.uint() )

      # Message is from a bmark

      elif msg_type == 2:

        if msg_xtra == 0:
          print( "" )
          print( "  [ passed ]##" )
          print( "" )
          break

        else:
          app_fail_xtra = True

      # Message is from print

      elif msg_type == 3:
        app_print = True
        app_print_type = msg_xtra
        if app_print_type not in [0,1,2]:
          print("ERROR: received unrecognized app print type!")
          exit(1)

    # Tick the simulator

    model.tick()

  end_time = timeit.default_timer()

  #-----------------------------------------------------------------------
  # Post processing
  #-----------------------------------------------------------------------

  # Force a test failure if we timed out

  if count >= opts.limit:
    print("""
   ERROR: Exceeded maximum number of cycles ({}). Your
   application might be in an infinite loop, or you need to use the
   --limit command line option to increase the limit.
    """.format(opts.limit))
    exit(1)

  # Display stats

  if opts.stats:
    print("num_cycles = ""##", num_cycles)

  if opts.perf > 0:
    print()
    print( "---------- Simulation performance ----------" )
    print( "- Total cycles   : %d cycles" % count )
    print( "- Execution time : %.5f seconds" % (end_time - start_time) )
    print( "- Cycle/second   : %.2f cps" % (count/(end_time - start_time)) )
    print()

  exit(0)

main()

