#=========================================================================
# Synopsys PTPX -- Generate .lib and .db
#=========================================================================

name: synopsys-ptpx-genlibdb

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.vcs.v
  - design.spef.gz
  - design.pt.sdc

outputs:
  - design.lib
  - design.db

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - pt_shell -file START.tcl
  - mkdir -p outputs && cd outputs
  - ln -sf ../*.db  design.db
  - ln -sf ../*.lib design.lib

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
  order:

