#=========================================================================
# Mentor Calibre GDS Merge
#=========================================================================
# Author : Christopher Torng
# Date   : November 5, 2019
#

name: mentor-calibre-gdsmerge

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - design.gds.gz
  - openram-gds.list
  - adk

outputs:
  - design_merged.gds

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------


commands:
  - sh run.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - calibredrv -m design_merged.gds \
               -l inputs/adk/calibre.layerprops

