#!/usr/bin/env python
#=========================================================================
# lab1-sim [options]
#=========================================================================
#
#  -h --help           Display this message
#
#  --impl              {rtl-scycle,rtl-fixed,rtl-var,rtl-nstage}
#  --nstages           Number of pipeline stages for nstage models
#  --input <dataset>   {small,large,lomask,himask,lohimask,sparse}
#  --trace             Display line tracing
#  --stats             Display statistics
#  --translate         Translate RTL model to Verilog
#  --dump-vcd          Dump VCD to imul-<impl>-<input>.vcd
#
# Author : Christopher Batten, Shunning Jiang
# Date   : February 5, 2015
#

# Hack to add project root to python path

import os
import sys

sim_dir = os.path.dirname( os.path.abspath( __file__ ) )
while sim_dir:
  if os.path.exists( sim_dir + os.path.sep + ".pymtl_sim_root" ):
    sys.path.insert(0,sim_dir)
    break
  sim_dir = os.path.dirname(sim_dir)

import argparse
import re

from pymtl3             import *
from pymtl3.stdlib.test import config_model
from pymtl3.passes.backends.verilog import VerilogPlaceholderPass

# from lab1_imul.IntMulFixedLatCL  import IntMulFixedLatCL
# from lab1_imul.IntMulVarLatCL    import IntMulVarLatCL
# from lab1_imul.IntMulNstageCL    import IntMulNstageCL
from lab1_imul.IntMulScycleRTL   import IntMulScycleRTL
from lab1_imul.IntMulFixedLatRTL import IntMulFixedLatRTL
from lab1_imul.IntMulVarLatRTL   import IntMulVarLatRTL
from lab1_imul.IntMulNstageRTL   import IntMulNstageRTL

from lab1_imul.test.IntMulFixedLatRTL_test import TestHarness
from lab1_imul.test.IntMulFixedLatRTL_test import random_small_msgs, random_large_msgs
from lab1_imul.test.IntMulFixedLatRTL_test import random_lomask_msgs, random_himask_msgs
from lab1_imul.test.IntMulFixedLatRTL_test import random_lohimask_msgs, random_sparse_msgs

#-------------------------------------------------------------------------
# Command line processing
#-------------------------------------------------------------------------

class ArgumentParserWithCustomError(argparse.ArgumentParser):
  def error( self, msg = "" ):
    if ( msg ): print("\n ERROR: %s" % msg)
    print("")
    file = open( sys.argv[0] )
    for ( lineno, line ) in enumerate( file ):
      if ( line[0] != '#' ): sys.exit(msg != "")
      if ( (lineno == 2) or (lineno >= 4) ): print( line[1:].rstrip("\n") )

def parse_cmdline():
  p = ArgumentParserWithCustomError( add_help=False )

  # Standard command line arguments

  p.add_argument( "-h", "--help",    action="store_true" )

  # Additional commane line arguments for the simulator

  p.add_argument( "--impl", default="rtl-scycle",
    choices=[
      # "cl-fixed","cl-var","cl-nstage",
      "rtl-scycle","rtl-fixed","rtl-var","rtl-nstage",
    ] )

  p.add_argument( "--nstages", default=2 )

  p.add_argument( "--input", default="small",
    choices=["small","large","lomask","himask","lohimask","sparse"] )

  p.add_argument( "--trace",     action="store_true" )
  p.add_argument( "--stats",     action="store_true" )
  p.add_argument( "--translate", action="store_true" )
  p.add_argument( "--dump-vcd",  action="store_true" )

  opts = p.parse_args()
  if opts.help: p.error()
  return opts

#-------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------

def main():
  opts = parse_cmdline()

  # Create the input pattern

  inputs  = None

  if   opts.input == "small":    inputs = random_small_msgs
  elif opts.input == "large":    inputs = random_large_msgs
  elif opts.input == "lomask":   inputs = random_lomask_msgs
  elif opts.input == "himask":   inputs = random_himask_msgs
  elif opts.input == "lohimask": inputs = random_lohimask_msgs
  elif opts.input == "sparse":   inputs = random_sparse_msgs

  ninputs = len(inputs[::2])

  # Determine which model to use in the simulator

  model_impl_dict = {
    # "cl-fixed"  : IntMulFixedLatCL,
    # "cl-var"    : IntMulVarLatCL,
    # "cl-nstage" : IntMulNstageCL,
    "rtl-scycle": IntMulScycleRTL,
    "rtl-fixed" : IntMulFixedLatRTL,
    "rtl-var"   : IntMulVarLatRTL,
    "rtl-nstage": IntMulNstageRTL,
  }

  # Check if translation is valid

  if opts.translate and not opts.impl.startswith("rtl"):
    print("\n ERROR: --translate only works with RTL models \n")
    exit(1)

  # Create VCD filename

  if opts.dump_vcd:
    if opts.impl.endswith("nstage"):
      vcd_file_name = f"imul-rtl-{int(opts.nstages)}stage-{opts.input}"
    else:
      vcd_file_name = f"imul-{opts.impl}-{opts.input}"
  else:
    vcd_file_name = ""

  # Parameters

  params = {}
  if opts.impl.endswith("nstage"):
    params = { "nstages" : int(opts.nstages) }

  # Create test harness (we can reuse the harness from unit testing)

  th = TestHarness( model_impl_dict[ opts.impl ]( **params ) )

  th.set_param("top.tm.src.construct",  msgs=inputs[::2] )
  th.set_param("top.tm.sink.construct", msgs=inputs[1::2] )

  # Configure the test harness component

  config_model( th, vcd_file_name, opts.translate, ['imul'] )

  # Setup the test harness

  th.elaborate()

  # Apply placeholder pass

  th.apply ( VerilogPlaceholderPass() )

  # We can call apply if we are 100% sure the top level is not tagged

  th.apply( TranslationImportPass() )

  # Create a simulator

  th.apply( SimulationPass() )

  # Reset test harness

  th.sim_reset( print_line_trace=opts.trace )

  # 2 cycles to reset

  ncycles = 2

  # Run simulation

  while not th.done():
    if opts.trace:
      th.print_line_trace()

    th.tick()
    ncycles += 1

  # Extra ticks to make VCD easier to read

  th.tick()
  th.tick()
  th.tick()

  # Display statistics

  if opts.stats:
    print( f"num_cycles         = {ncycles}" )
    print( f"num_cycles_per_mul = {ncycles/(1.0*ninputs):1.2f}" )

main()
