#include "stdint.h"
#include <stdio.h>
#include <stdlib.h>
#include "common.h"

// include the sub-function located in /../app/ubmark/ubmark-oflow-function/
#include "ubmark-oflow-function/image_parameters.h"
#include "ubmark-oflow-function/oflow-corner-decoder.c"
#include "ubmark-oflow-function/oflow-corner-decoder-5x5.c"
#include "ubmark-oflow-function/oflow-derivative-t.c"
#include "ubmark-oflow-function/oflow-derivative-x.c"
#include "ubmark-oflow-function/oflow-derivative-y.c"
#include "ubmark-oflow-function/oflow-matrix-2x2-multi-2x1.c"
#include "ubmark-oflow-function/oflow-matrix-inverse-2x2.c"
#include "ubmark-oflow-function/oflow-matrix-multi.c"
#include "ubmark-oflow-function/oflow-pixel-sum.c"

// include the input arrays generated by MATLAB
#include "MATLAB_app/result_MATLAB/result_data/image_data_3d.dat"
#include "MATLAB_app/result_MATLAB/result_data/corner_x_coordi.dat"
#include "MATLAB_app/result_MATLAB/result_data/corner_y_coordi.dat"
#include "MATLAB_app/result_MATLAB/result_data/corner_nums.dat"

// include the reference arrays to check the result of the baseline
#include "MATLAB_app/result_MATLAB/result_data/vx_ref.dat"
#include "MATLAB_app/result_MATLAB/result_data/vy_ref.dat"
#include "MATLAB_app/result_MATLAB/result_data/de_ref.dat"

void write_output_data (
    int32_t vx, 
    int32_t vy, 
    int32_t determinant, 
    int32_t image1[5][5], 
    int32_t image2[5][5],
    int32_t corner_x,
    int32_t corner_y) {

    int i,j;

    FILE *datFile;
    datFile = fopen("native-output-data.dat", "wb");
    if (datFile == NULL) {
        printf("Error on opening the file! \n");
    }
    else {
        for (i=0; i<5; i++) {
            for (j=0; j<5; j++) {
                fprintf(datFile, "%i ", image1[i][j]);
            }
        }

        fclose(datFile);
        printf("successfully write! \n");
  }
}  

void verify_results (
     int32_t vx[],
     int32_t vy[],
     int32_t de[],
     int32_t vx_ref[],
     int32_t vy_ref[],
     int32_t de_ref[] ) 
{
     int32_t i;

     for (i=0; i< (image_number)*corner_number; i++) {
         if ( !(vx[i] == vx_ref[i]) ) {
             test_fail( i, vx[i], vx_ref[i] );
         }

         if ( !(vy[i] == vy_ref[i]) ) {
             test_fail( i, vy[i], vy_ref[i] );
         }

         if ( !(de[i] == de_ref[i]) ) {
             test_fail( i, de[i], de_ref[i] );
         }
     }  
 
     test_pass();
}

int main () {

    int i, j, corner_cnt;
    int32_t image_1[image_in_rows][image_in_cols];
    int32_t image_2[image_in_rows][image_in_cols];
    int32_t image_derivate_x[num_rows][num_cols];
    int32_t image_derivate_y[num_rows][num_cols];
    int32_t image_derivate_t[num_rows][num_cols];
    int32_t image_lx_square[num_rows][num_cols];
    int32_t image_ly_square[num_rows][num_cols];
    int32_t image_lx_mul_ly[num_rows][num_cols];
    int32_t image_lx_mul_lt[num_rows][num_cols];
    int32_t image_ly_mul_lt[num_rows][num_cols];
    int32_t image_lx_square_sum;
    int32_t image_ly_square_sum;
    int32_t image_lx_mul_ly_sum;
    int32_t image_lx_mul_lt_sum;
    int32_t image_ly_mul_lt_sum;
    int32_t c_x, c_y;
    int32_t u_v_raw[2];
    int32_t vx[image_number * corner_number];
    int32_t vy[image_number * corner_number];
    int32_t de[image_number * corner_number];

    int32_t image_corner_window1[num_rows][num_cols];
    int32_t image_corner_window2[num_rows][num_cols];
    int32_t image_corner_window1_5x5[5][5];
    int32_t image_corner_window2_5x5[5][5];

    int32_t determinant;
    int     third_dimension;

    for (third_dimension=0; third_dimension<image_number; third_dimension++) {
 
        for (i=0; i<image_in_rows; i++) {
            for (j=0; j<image_in_cols; j++) {
                image_1[i][j] = image_set_3d[third_dimension][i][j];
            }
        }

        for (i=0; i<image_in_rows; i++) {
            for (j=0; j<image_in_cols; j++) {
                image_2[i][j] = image_set_3d[third_dimension+1][i][j];
            }
        }

        for (corner_cnt=0; corner_cnt<corner_number; corner_cnt++) {

            c_x = corner_x[third_dimension][corner_cnt];
            c_y = corner_y[third_dimension][corner_cnt];

            //image_1_num=read_image_data(image_1, "test_small.dat");
            corner_decoder(c_x, c_y, image_1, image_2, image_corner_window1, image_corner_window2);
            printf("corner window 1 is: \n");
            for (i=0; i<num_rows; i++) {
                for (j=0; j<num_cols; j++) {
                    printf("%i,", image_corner_window1[i][j]);
                }
                printf("\n");
            };
            printf("=====================!! \n");

            corner_decoder_5x5(c_x, c_y, image_1, image_2, image_corner_window1_5x5, image_corner_window2_5x5);
            printf("corner window 1 5x5 is: \n");
            for (i=0; i<5; i++) {
                for (j=0; j<5; j++) {
                    printf("%i,", image_corner_window1_5x5[i][j]);
                }
                printf("\n");
            };
            printf("=====================!! \n");

            printf("corner window 2 5x5 is: \n");
            for (i=0; i<5; i++) {
                for (j=0; j<5; j++) {
                    printf("%i,", image_corner_window2_5x5[i][j]);
                }
                printf("\n");
            };
            printf("=====================!! \n");

            image_sptial_derivate_x(image_1, image_derivate_x, c_x, c_y);
            printf("Ix is: \n");
            for (i=0; i<num_rows; i++) {
                for (j=0; j<num_cols; j++) {
                    printf("%i,", image_derivate_x[i][j]);
                }
                printf("\n");
            };
            printf("=====================!! \n");

            image_sptial_derivate_y(image_1, image_derivate_y, c_x, c_y);
            printf("Iy is: \n");
            for (i=0; i<num_rows; i++) {
                for (j=0; j<num_cols; j++) {
                    printf("%i,", image_derivate_y[i][j]);
                }
                printf("\n");
            };
            printf("=====================!! \n");

            image_sptial_derivate_t(image_corner_window1, image_corner_window2, image_derivate_t);
            printf("It is: \n");
            for (i=0; i<num_rows; i++) {
                for (j=0; j<num_cols; j++) {
                    printf("%i,", image_derivate_t[i][j]);
                }
                printf("\n");
            };
            printf("=====================!! \n");

            image_multiplication(image_derivate_x, image_derivate_x, image_lx_square);
            printf("Ix square is: \n");
            for (i=0; i<num_rows; i++) {
                for (j=0; j<num_cols; j++) {
                    printf("%i,", image_lx_square[i][j]);
                } 
                printf("\n");
            };
            printf("=====================!! \n");

            image_multiplication(image_derivate_y, image_derivate_y, image_ly_square);
            printf("Iy square is: \n");
            for (i=0; i<num_rows; i++) {
                for (j=0; j<num_cols; j++) {
                    printf("%i,", image_ly_square[i][j]);
                }
                printf("\n");
            };
            printf("=====================!! \n");
    
            image_multiplication(image_derivate_x, image_derivate_y, image_lx_mul_ly);
            printf("Ix * ly is: \n");
            for (i=0; i<num_rows; i++) {
                for (j=0; j<num_cols; j++) {
                    printf("%i,", image_lx_mul_ly[i][j]);
                }
                printf("\n");
            };
            printf("=====================!! \n");

            image_multiplication(image_derivate_x, image_derivate_t, image_lx_mul_lt);
            printf("Ix * lt is: \n");
            for (i=0; i<num_rows; i++) {
                for (j=0; j<num_cols; j++) {
                        printf("%i,", image_lx_mul_lt[i][j]);
                }
                printf("\n");
            };
            printf("=====================!! \n");

            image_multiplication(image_derivate_y, image_derivate_t, image_ly_mul_lt);
            printf("Iy * lt is: \n");
            for (i=0; i<num_rows; i++) {
                for (j=0; j<num_cols; j++) {
                    printf("%i,", image_ly_mul_lt[i][j]);
                }
                printf("\n");
            };
            printf("=====================!! \n");

            image_lx_square_sum = image_pixel_sum(image_lx_square);
            image_ly_square_sum = image_pixel_sum(image_ly_square);
            image_lx_mul_ly_sum = image_pixel_sum(image_lx_mul_ly);
            image_lx_mul_lt_sum = image_pixel_sum(image_lx_mul_lt);
            image_ly_mul_lt_sum = image_pixel_sum(image_ly_mul_lt);
            image_lx_mul_lt_sum = image_lx_mul_lt_sum * (-1);
            image_ly_mul_lt_sum = image_ly_mul_lt_sum * (-1);
            printf("lx_square_sum is %i \n", image_lx_square_sum);
            printf("ly_square_sum is %i \n", image_ly_square_sum);
            printf("lx X ly sum is %i \n", image_lx_mul_ly_sum);
            printf("lx X lt sum is %i \n", image_lx_mul_lt_sum);
            printf("ly X lt sum is %i \n", image_ly_mul_lt_sum);
            printf("=====================!! \n");

            // organize the 2x2 martix
            int32_t matrix_2x2[2][2] = {0,0,0,0};
            matrix_2x2[0][0] = image_lx_square_sum;
            matrix_2x2[0][1] = image_lx_mul_ly_sum;
            matrix_2x2[1][0] = image_lx_mul_ly_sum;
            matrix_2x2[1][1] = image_ly_square_sum;
            printf("The pre- 2x2 matrix is: \n");
            for (i=0; i<2; i++) {
                for (j=0; j<2; j++) {
                    printf("%i,", matrix_2x2[i][j]);
                }
                printf("\n");
            };
            printf("=====================!! \n");

            determinant  = image_matrix_inverse_2x2(matrix_2x2);
            printf("The determinant is %i: \n", determinant);
            printf("The 2x2 matrix is: \n");
            for (i=0; i<2; i++) {
                for (j=0; j<2; j++) {
                    printf("%i,", matrix_2x2[i][j]);
                }
                printf("\n");
            };
            printf("=====================!! \n");

            int32_t matrix_2x1[2] = {0,0};
            matrix_2x1[0] = image_lx_mul_lt_sum;
            matrix_2x1[1] = image_ly_mul_lt_sum;
            image_2x2_multi_2x1(matrix_2x2, matrix_2x1, u_v_raw);

            vx[third_dimension*corner_number+corner_cnt] = u_v_raw[0];
            vy[third_dimension*corner_number+corner_cnt] = u_v_raw[1];
            de[third_dimension*corner_number+corner_cnt] = determinant;

            printf("raw u is %i \n", u_v_raw[0]);
            printf("raw v is %i \n", u_v_raw[1]);
            printf("=====================!! \n");


            //write_image_data(image_1);
            printf("corner_x is %i \n", c_x);
            printf("corner_y is %i \n", c_y);
            printf("corner_cnt now is %i \n", corner_cnt);
            printf("currently is on %i \n", third_dimension);

            
        }

    }

    write_output_data(u_v_raw[0], u_v_raw[1], determinant, image_corner_window1_5x5, image_corner_window2_5x5, c_x, c_y);

    printf("==========!!!!!!!! \n");

    verify_results(vx, vy, de, vx_ref, vy_ref, de_ref);

    return 0;

}
