#!/usr/bin/env python
#=========================================================================
# sort-xcel-sim [options]
#=========================================================================
#
#  -h --help           Display this message
#
#  --impl              {fl,cl,rtl}
#  --input <dataset>   {random,sorted-fwd,sorted-rev}
#  --trace             Display line tracing
#  --stats             Display statistics
#  --translate         Translate RTL model to Verilog
#  --dump-vcd          Dump VCD to imul-<impl>-<input>.vcd
#
# Author : Christopher Batten
# Date   : March 16, 2015
#


# Hack to add project root to python path

import os
import sys

sim_dir = os.path.dirname( os.path.abspath( __file__ ) )
while sim_dir:
  if os.path.exists( sim_dir + os.path.sep + ".pymtl_sim_root" ):
    sys.path.insert(0,sim_dir)
    break
  sim_dir = os.path.dirname(sim_dir)

import argparse
import re
import struct

from random               import randint

from pymtl3                import *
from pymtl3.stdlib.test import config_model
from pymtl3.passes.backends.verilog import VerilogPlaceholderPass

from lab2_xcel          import SortXcelFL
from lab2_xcel          import SortXcelCL
from lab2_xcel          import SortXcelRTL
from proc.XcelMsg       import *

from lab2_xcel.test.SortXcelFL_test import TestHarness
from lab2_xcel.test.SortXcelFL_test import large_data, sort_fwd_data, sort_rev_data

#-------------------------------------------------------------------------
# Command line processing
#-------------------------------------------------------------------------

class ArgumentParserWithCustomError(argparse.ArgumentParser):
  def error( self, msg = "" ):
    if ( msg ): print("\n ERROR: %s" % msg)
    print("")
    file = open( sys.argv[0] )
    for ( lineno, line ) in enumerate( file ):
      if ( line[0] != '#' ): sys.exit(msg != "")
      if ( (lineno == 2) or (lineno >= 4) ): print( line[1:].rstrip("\n") )

def parse_cmdline():
  p = ArgumentParserWithCustomError( add_help=False )

  # Standard command line arguments

  p.add_argument( "-h", "--help",    action="store_true" )

  # Additional commane line arguments for the simulator

  p.add_argument( "--impl", default="fl", choices=["fl","cl","rtl"] )

  p.add_argument( "--input", default="random",
    choices=["random","sorted-fwd","sorted-rev"] )

  p.add_argument( "--trace",     action="store_true" )
  p.add_argument( "--stats",     action="store_true" )
  p.add_argument( "--translate", action="store_true" )
  p.add_argument( "--dump-vcd",  action="store_true" )

  opts = p.parse_args()
  if opts.help: p.error()
  return opts

#-------------------------------------------------------------------------
# make messages
#-------------------------------------------------------------------------

def req( type_, raddr, data ):
  return XcelReqMsg(XCEL_TYPE_READ if type_ == 'rd' else XCEL_TYPE_WRITE, raddr, data)

def resp( type_, data ):
  return XcelRespMsg(XCEL_TYPE_READ if type_ == 'rd' else XCEL_TYPE_WRITE, data)

#-------------------------------------------------------------------------
# Xcel Protocol
#-------------------------------------------------------------------------
# These are the source sink messages we need to configure the accelerator
# and wait for it to finish. We use the same messages in all of our
# tests. The difference between the tests is the data to be sorted in the
# test memory.

def gen_xcel_protocol_msgs( size ):
  return [
    req( 'wr', 1, 0x1000 ), resp( 'wr', 0 ),
    req( 'wr', 2, size   ), resp( 'wr', 0 ),
    req( 'wr', 0, 0      ), resp( 'wr', 0 ),
    req( 'rd', 0, 0      ), resp( 'rd', 1 ),
  ]

#-------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------

def main():
  try:
    import pypyjit
    pypyjit.set_param("off")
  except:
    pass

  opts = parse_cmdline()

  # Create the input pattern

  data = None

  if   opts.input == "random":     data = large_data
  elif opts.input == "sorted-fwd": data = sort_fwd_data
  elif opts.input == "sorted-rev": data = sort_rev_data

  ninputs = len(data[::2])

  # Determine which model to use in the simulator

  model_impl_dict = {
    "fl"  : SortXcelFL,
    "cl"  : SortXcelCL,
    "rtl" : SortXcelRTL,
  }

  # Check if translation is valid

  if opts.translate and not opts.impl.startswith("rtl"):
    print("\n ERROR: --translate only works with RTL models \n")
    exit(1)

  if opts.dump_vcd and not opts.impl.startswith("rtl"):
    print("\n ERROR: --dump-vcd only works with RTL models \n")
    exit(1)

  # Create VCD filename

  if opts.dump_vcd:
    vcd_file_name = f"sort-xcel-{opts.impl}-{opts.input}"
  else:
    vcd_file_name = ""

  # Convert test data into byte array

  data_bytes = struct.pack("<{}I".format(len(data)),*data)

  # Protocol messages

  xcel_protocol_msgs = gen_xcel_protocol_msgs( len(data) )

  # Create test harness (we can reuse the harness from unit testing)

  th = TestHarness( model_impl_dict[ opts.impl ]() )

  # Load the data

  th.set_param("top.tm.src.construct",  msgs=xcel_protocol_msgs[::2] )
  th.set_param("top.tm.sink.construct", msgs=xcel_protocol_msgs[1::2] )

  # Configure the test harness component

  config_model( th, vcd_file_name, opts.translate, ['xcel'] )

  th.mem.write_mem( 0x1000, data_bytes )

  # Apply placeholder pass

  th.apply ( VerilogPlaceholderPass() )

  # We can call apply if we are 100% sure the top level is not tagged

  th.apply( TranslationImportPass() )

  # Create a simulator

  th.apply( SimulationPass() )

  # Reset test harness

  th.sim_reset( print_line_trace=opts.trace )

  # Run simulation
  ncycles = 2

  while not th.done():

    if opts.trace:
      th.print_line_trace()

    th.tick()
    ncycles += 1

  # Extra ticks to make VCD easier to read

  th.tick()
  th.tick()
  th.tick()

  # Retrieve data from test memory

  result_bytes = th.mem.read_mem( 0x1000, len(data_bytes) )

  # Convert result bytes into list of ints

  result = list(struct.unpack("<{}I".format(len(data)),bytearray(result_bytes)))

  # Compare result to sorted reference

  assert result == sorted(data)

  # Display statistics

  if opts.stats:
    print( "num_cycles = {}".format( ncycles ) )

main()
