#=========================================================================
# Generate DB for LIB files
#=========================================================================
# Author : Khalid Al-Hawaj
# Date   : Feb 25, 2020
#

name: openram-generate-db

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - openram-lib.list

outputs:
  - openram-db.list

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - sh ./run.sh
