#=========================================================================
# Generate OpenRAM Configurations
#=========================================================================
# Author : Khalid Al-Hawaj
# Date   : Feb 13, 2020
#

name: openram-generate

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - openram-cfg.list

outputs:
  - openram-sp.list
  - openram-gds.list
  - openram-v.list
  - openram-lib.list
  - openram-lef.list

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - sh ./run.sh
